# Generated by Django 5.2.6 on 2025-09-26 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawlings', '0002_comment_delete_stock_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Stock_code',
            new_name='stock_code',
        ),
    ]
